### ISSUE TITLE
Email address validation is too strict 

### ISSUE THREAD

**Issue by passsy** [wiredashio/wiredash-sdk#1]
Some email addresses are reported as invalid although they are valid. I noticed it for `live` TLDs.

```dart
Wiredash.of(context).setOptions(userEmail: "me@flutter.live");
```

This results in an error when sending it to the server

```
500:
{\"message\":\"Feedback validation failed: email: Not a valid email address\"}
```

Either the email validation should also happen in the client sdk when calling `setOptions` or the server should ignore it entirely.

A rather simple but working Regex would be `^\S+@\S+\.\S+$`.

**Comment by flschweiger** [comment]
Thanks for the heads up - this should be fixed now 🙂

**Comment by passsy** [comment]
I can confirm it is fixed ❤️
