### ISSUE TITLE
[Proposal] Add option to launch Wiredash fix context-specific configurations

### ISSUE THREAD

**Issue by GroovinChip** [wiredashio/wiredash-sdk#10]
For example: in the case of unhandled or unexpected errors, I show a button to my user with a prompt to report the error/bug to me. Pressing the button opens Wiredash.

I would like be able to configure Wiredash such that I can jump a user straight into the "report a bug" mode. I figure adding optional parameters to `show()` would do the trick, like `wiredashMode` and maybe a `config` to show different `WiredashConfig`s for different contexts. If left blank they would obviously default to the default mode and `WiredashConfig`

**Comment by flschweiger** [comment]
That's a pretty cool idea 👍

**Comment by GroovinChip** [comment]
Another thing that would be great is being able to include logs when sending a bug report

**Comment by Nash0x7E2** [comment]
The addition of logs would be cool but it would come at a later date.

**Comment by GroovinChip** [comment]
That's fine, that's just icing on the cake for me. The main things I'm interested in are contextual theming and contextual feedback modes.
