### ISSUE TITLE
Wrap with MaterialApp

### ISSUE THREAD

**Issue by Presheda** [wiredashio/wiredash-sdk#101]
is there a way to integrate without wrapping material app with Wiredash?? I'm already using a package that requires to be my root project to be wrap with a specific widget.  I'm using the Get package  [https://pub.dev/packages/get](url) 

and my root widget looks like this 

```
class HelloApp extends StatelessWidget {
   @override
   Widget build(BuildContext context) {

    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
        initialRoute: RouteName.splash_screen,
        getPages: RouteName.getPages(),

    );
  }
}

```

**Comment by brianegan** [comment]
Hi @Presheda  -- `GetMaterialApp` is just a wrapper around `MaterialApp`, but there's no reason you can't wrap that as well!

You should be able to wrap a `GetMaterialApp` like so:


```dart
return Wiredash(
  projectId: "YOUR-PROJECT-ID",
  secret: "YOUR-SECRET",
  navigatorKey: Get.key, // use the navigatorKey provided by the `Get` package
  child: GetMaterialApp(
      debugShowCheckedModeBanner: false,
      initialRoute: RouteName.splash_screen,
      getPages: RouteName.getPages(),
  ),
);
```

Please let me know if that causes any issues!

**Comment by flschweiger** [comment]
@atoka93 @passsy I think it would be awesome if we could add some samples to a specific section in the 'Getting Started' guide where we show how to use Wiredash with some of the different state management libraries 📝

**Comment by adiltirur** [comment]
> Hi @Presheda -- `GetMaterialApp` is just a wrapper around `MaterialApp`, but there's no reason you can't wrap that as well!
> 
> You should be able to wrap a `GetMaterialApp` like so:
> 
> ```dart
> return Wiredash(
>   projectId: "YOUR-PROJECT-ID",
>   secret: "YOUR-SECRET",
>   navigatorKey: Get.key, // use the navigatorKey provided by the `Get` package
>   child: GetMaterialApp(
>       debugShowCheckedModeBanner: false,
>       initialRoute: RouteName.splash_screen,
>       getPages: RouteName.getPages(),
>   ),
> );
> ```
> 
> Please let me know if that causes any issues!

I am facing the same issue. I have the Get package and when I use 

`navigatorKey: Get.key,`

as you suggested  I get 

Duplicate GlobalKey detected in widget tree.

Do you have a solution that can may be help me ?

**Comment by atoka93** [comment]
@Presheda @adiltirur 

After combining the Wiredash example `main.dart`:
https://github.com/wiredashio/wiredash-sdk/blob/46de95be6ce44c4be917f247880c9b9549358752/example/lib/main.dart#L35-L38
and the getx example `main.dart`:
https://github.com/jonataslaw/getx/blob/7cbb9fb8b1294acd339b2adbc18a389e6c3561c1/example/lib/main.dart
I ended up with this working solution:
```
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:wiredash/wiredash.dart';

import 'lang/translation_service.dart';
import 'routes/app_pages.dart';
import 'shared/logger/logger_utils.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final GlobalKey<NavigatorState> _navigatorKey = GlobalKey<NavigatorState>();

  @override
  Widget build(BuildContext context) {
    return Wiredash(
      projectId: "Project ID from console.wiredash.io",
      secret: "API Key from console.wiredash.io",
      navigatorKey: _navigatorKey,
      // use the navigatorKey provided by the `Get` package
      child: GetMaterialApp(
        navigatorKey: _navigatorKey,
        debugShowCheckedModeBanner: false,
        enableLog: true,
        logWriterCallback: Logger.write,
        initialRoute: AppPages.INITIAL,
        getPages: AppPages.routes,
        locale: TranslationService.locale,
        fallbackLocale: TranslationService.fallbackLocale,
        translations: TranslationService(),
      ),
    );
  }
}
```

The relevant changes are making the `MyApp` a stateful widget and adding a custom navigator key to both `Wiredash` and `GetMaterialApp`.

**Comment by atoka93** [comment]
Let us know if that works for you 🙂

**Comment by RicardoRB** [comment]
Hi guys! Is there any support for [MaterialApp.router](https://api.flutter.dev/flutter/material/MaterialApp/MaterialApp.router.html)?

**Comment by passsy** [comment]
Wiredash 1.0.0 has removed the need for `navigatorKey`. It can now be placed easily around `MaterialApp.router`.

It can even be placed below `MaterialApp`, inside `builder` https://docs.wiredash.io/sdk/localization/#access-locale-from-materialapp
