### ISSUE TITLE
Email integration

### ISSUE THREAD

**Issue by quantosapplications** [wiredashio/wiredash-sdk#107]
Hello, is possible to set the answer to field for email integration with the reporter email?
We would like to integrate wiredash with fresh desk so when a feedback gets created on wire dash it gets created on fresh desk too which will send an automatic email to the reporter.

**Comment by flschweiger** [comment]
Hi, that's a cool idea! We'll take the feature and add it to our backlog 👍

**Comment by flschweiger** [comment]
Hi @quantosapplications, we've just released this feature 🎉  Now every email notification will automatically have the reply-to field set to the reporter's email if there's one 🙂

Stay safe and have a nice holiday!
