### ISSUE TITLE
Null Navigator Context

### ISSUE THREAD

**Issue by searchy2** [wiredashio/wiredash-sdk#11]
Hmmm, it seems like Wiredash can't find the navigator. 

> Caught error: NoSuchMethodError: The method 'push' was called on null.
>     Receiver: null
>     Tried calling: push<dynamic>(Instance of 'DismissiblePageRoute<dynamic>')
> I/flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
>     #1      WiredashStateData.show (package:wiredash/src/common/state/wiredash_state_data.dart:111:10)
>     #2      WiredashController.show (package:wiredash/src/wiredash_controller.dart:36:30)

```
class App extends StatelessWidget {
  final _navigatorKey = GlobalKey<NavigatorState>();
  @override
  Widget build(BuildContext context) {
    return Wiredash(
      projectId: "",
      secret: "",
      navigatorKey: _navigatorKey,
      child: MaterialApp(
        title: 'Wiredash',
        home: Home(),
      ),
    );
  }
}
```

```

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  void reportError() {
    Wiredash.of(context).show();
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Container(
            width: double.infinity,
            height: double.infinity,
            child: Column(
              children: <Widget>[
                MaterialButton(
                  onPressed: () => reportError(),
                  color: Colors.blueGrey,
                  child: Text("Report Error",
                      style: TextStyle(color: Colors.white)),
                ),
              ],
            ),
        ),
      ),
    );
  }
}

```

I tried both the widget context and the global context. Both reported an error.

Am I doing something wrong?

**Comment by searchy2** [comment]
Doh!

Add the navigator key to both Wiredash AND the MaterialApp.

**Comment by flschweiger** [comment]
Hey @searchy2 , thanks for creating this issue - it helps a lot build a better tool 👍 The upcoming release will print a way better error message to the console with the instructions on how to get this fixed. 

If you have any other comments / wishes feel free to reach out to me or simply create a new issue :)
