### ISSUE TITLE
Use Wiredash in two different places with different configurations

### ISSUE THREAD

**Issue by masfour7** [wiredashio/wiredash-sdk#114]
I'm trying to use Wiredash in two different places in my app and use different options and/or translation in each place. I could not find a way to perform this. Is it possible?

**Comment by flschweiger** [comment]
Hi @masfour7, currently Wiredash can only be configured 'globally' so that would be difficult to achieve 🤔  Why would you need to have two different configurations? For internal testing? Would be glad to help you find a solution :)

**Comment by masfour7** [comment]
One for its original use: user feedback. Also, I thought I could use it when the user wants to report some content in the app. I would need to have different text and only one report button shown. Do you have any recommendations for that?

**Comment by passsy** [comment]
Hey @masfour7,

You can change the properties of the Wiredash Widget like any other Widget using state management. When a user visits a certain screen, change your app state and update the `Wiredash` Widget accordingly. 


```dart

if (env == 'dev') {
  return Wiredash(
    projectId: 'bbb',
    secret: '...',
    feedbackOptions: WiredashFeedbackOptions(
      labels: [
        Label(id: 'label-en6zgtnbp4', title: 'Improvement'),
        Label(id: 'label-hqxknn7820', title: 'Praise'),
        Label(id: 'label-hqxknn7820', title: 'Bug'),
      ],
      collectMetaData: (metadata) => metadata
        ..userId = 'reply-userid'
        ..custom['nested'] = {
          'inbox': {'items': 8, 'total': 124, 'mode': 'smart'}
        },
    ),
    child: app,
  );
}

return Wiredash(
  projectId: 'aaa',
  secret: '...',
  feedbackOptions: WiredashFeedbackOptions(
    labels: [
      Label(id: 'label-9qjzjebxl7', title: 'Ein gutes label'),
      Label(id: 'label-ahczpfeos8', title: 'Bug'),
      Label(id: 'unknown', title: 'unknown'),
    ],
    collectMetaData: (metadata) => metadata
      ..custom['nested'] = {
        'emails_read_today': 13,
      },
  ),
  child: app,
);

```
