### ISSUE TITLE
Azure Boards (Devops) integration

### ISSUE THREAD

**Issue by SogoGolf** [wiredashio/wiredash-sdk#116]
hey, thanks for the great (!) component. would be awesome if we could create (or add to) Azure Boards tickets!

https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20items/create?view=azure-devops-rest-6.0

**Comment by atoka93** [comment]
Hey @SogoGolf, could this be achieved using Wiredash -> Zapier -> Azure DevOps integrations? 🤔

**Comment by SogoGolf** [comment]
Good idea. Haven't used it in ages, how would Zapier know when a new item lands in Wiredash?

**Comment by passsy** [comment]
You can now connect all your favorite tools via Zapier, including Azure Devops

![zapier](https://docs.wiredash.io/images/zapier-dialog.png)

Checkout the docs https://docs.wiredash.io/integrations/zapier/
