### ISSUE TITLE
Please add danish translation from poeditor

### ISSUE THREAD

**Issue by janlektonen** [wiredashio/wiredash-sdk#119]
Hi - I love wiredash, so handy and pleasant and satisfying to use ;-)

But, I need the danish (da) translation updated ind this package. I can see that it is finalized on poeditor.com.

Please update the translation as soon as possible as I would like to go into production and need danish translation for my app.

Really great work you do,
best regards, Jan

**Comment by atoka93** [comment]
Hey @janlektonen 🙂 
The `da` translation should be available soon!

But in case you find yourself again in dire need of translations you could specify your own as shown here:
https://github.com/wiredashio/wiredash-sdk/blob/d7da5c894b7edc1470a08af11f5a48f7f3a20a47/example/lib/main.dart#L49

**Comment by passsy** [comment]
Available since [`v0.4.1`](https://github.com/wiredashio/wiredash-sdk/releases/tag/v0.4.1)

**Comment by janlektonen** [comment]
It seems like danish locale: const Locale('da', 'DK') is not yet available in the package @passsy ?

**Comment by passsy** [comment]
After the redesign for 1.0 the translations drastically changed. Unfortunately, danish has not been added again. Can you help us out? See [Localization - Contribute to Wiredash](https://docs.wiredash.io/sdk/localization/#contribute-to-wiredash)

**Comment by janlektonen** [comment]
Hi Pascal / @passsy 

Thanks for for your feedback,

Here is the file I have translated to danish (da-DK). It it a good translation I would say.

Please let me know if and when you include it.
[wiredash_da.arb.zip](https://github.com/wiredashio/wiredash-sdk/files/12000248/wiredash_da.arb.zip)

Best regards,
Jan Lektonen

**Comment by passsy** [comment]
Released in 1.7.2
