### ISSUE TITLE
How to show custom FeedbackType in the app

### ISSUE THREAD

**Issue by ujnamss** [wiredashio/wiredash-sdk#124]
Hi Folks,

Thanks for the great widget and SDK. I created a custom feedback type (label) on the server side. What configuration change do we need to do to "show" it in addition to default ["bug", "improvement", "praise"].

Thanks
Manju

**Comment by MichaelAshf** [comment]
Also interested in this. Any update? Also is it possible to configure the text that gets displayed per option, and whether a screenshot is requested?

**Comment by passsy** [comment]
You can add all labels from the console to your app like this

```dart
return Wiredash(
  // ...
  feedbackOptions: WiredashFeedbackOptions(
    labels: [
      // Take the label ids from your project console
      // https://console.wiredash.io/ -> Settings -> Labels
      Label(
        id: 'lbl-r65egsdf',
        title: 'Bug',
      ),
      Label(
        id: 'lbl-6543df23s',
        title: 'Feature Request',
      ),
      Label(
        id: 'lbl-2r98yas4',
        title: 'Payment',
      ),
    ],
  ),
);
```

For more information, like hidden labels see the documentation https://docs.wiredash.io/sdk/feedback-options/#labels
