### ISSUE TITLE
Warnings in 0.6.1 for null-aware operation

### ISSUE THREAD

**Issue by JamesCullum** [wiredashio/wiredash-sdk#134]
If I build with the newest version 0.6.1, I get the following warnings in Android Studio.

> ../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/wiredash-0.6.1/lib/src/common/options/wiredash_options_data.dart:17:33: Warning: Operand of null-aware operation '??' has type 'Locale' which excludes null.
>  - 'Locale' is from 'dart:ui'.
>         _currentLocale = locale ?? window.locale ?? const Locale('en', 'US'),
>                                 ^
> ../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/wiredash-0.6.1/lib/src/common/options/wiredash_options_data.dart:65:31: Warning: Operand of null-aware operation '??' has type 'Locale' which excludes null.
>  - 'Locale' is from 'dart:ui'.
>       _currentLocale = window.locale ?? const Locale('en', 'US');
>

**Comment by passsy** [comment]
Thanks for the report. The warning will disappear with [v0.6.2](https://github.com/wiredashio/wiredash-sdk/releases/tag/v0.6.2)

**Comment by JamesCullum** [comment]
Thanks a lot for the fast work, I can confirm that it's fixed now. 
One small note - I was not using the 1.27 dev channel, but the 2.0.1 stable one.
