### ISSUE TITLE
web: screenshot feature not available yet ...

### ISSUE THREAD

**Issue by gedw99** [wiredashio/wiredash-sdk#138]
Looks like the screenshot feature not available for web. 
Probably needs to use latest flutter update that support Texture widget.

https://github.com/wiredashio/wiredash-sdk/blob/stable/lib/src/feedback/feedback_sheet.dart#L234

**Comment by passsy** [comment]
Wiredash works for web when using canvaskit

```bash
flutter build web --web-renderer canvaskit
```

But taking a screenshot might crash when you embedd HTML elements on your site #118
