### ISSUE TITLE
support go-flutter ?

### ISSUE THREAD

**Issue by gedw99** [wiredashio/wiredash-sdk#139]
not sure if you are interested in supporting go-flutter.

I raised an issue with a work around fix here: https://github.com/go-flutter-desktop/go-flutter/issues/575

**Comment by RicardoRB** [comment]
Why using go-flutter when you have desktop compatibility native by flutter?

**Comment by passsy** [comment]
Nothing we can address in this package. Please raise an issue at `package: path_provider`
