### ISSUE TITLE
Screen flickers white on App start

### ISSUE THREAD

**Issue by mazzonem** [wiredashio/wiredash-sdk#144]
When using Wiredash 0.6.2 (visible when the phone using dark theme and the flutter theme brightness.dark), the screen flickers to white on App start.

How to reproduce:
- Turn on dark mode on your phone
- Change the default app theme to dark
- Apply wiredash with dark brightness
- Optionally put a delay before the Wiredash widget to see the dark theme
- Observe a white screen while Wiredash starts

Thanks in advance

**Comment by passsy** [comment]
Thanks for reporting! Can you see this in `debug` and `release` mode?

**Comment by drmacm** [comment]
I have the same problem. White screen when loading the app, between the splash screen and the first screen of the app. It happens in both debug and release modes.

Do you have plans on fixing this?

**Comment by passsy** [comment]
This is now resolved in wiredash 1.0.0. Please upgrade ⏫
