### ISSUE TITLE
Wiredash 0.7.0+1 doesnt work with ios

### ISSUE THREAD

**Issue by tjerkw** [wiredashio/wiredash-sdk#149]
../../../.pub-cache/hosted/pub.dartlang.org/wiredash-0.7.0+1/lib/src/common/device_info/dart_html_device_info_generator.dart:22:23: Error: Getter not found: 'window'.
          userAgent: html.window.navigator.userAgent,
                          ^^^^^^

**Comment by passsy** [comment]
Which flutter version are you using?

**Comment by passsy** [comment]
I'm cleaning up here. This has long been addressed. Please update ⏫ 👍
