### ISSUE TITLE
[Proposal] Export feedback.

### ISSUE THREAD

**Issue by pblinux** [wiredashio/wiredash-sdk#15]
Hi Wiredash team.

Sometimes, I need to show worked feedback as reports to external people or people that doesn't want to create an account.

It would be possible to add an export feature like, row data in csv or a pdf with current feedback items and it status?

**Comment by Nash0x7E2** [comment]
Hi! Thank you for your feedback. This feature is currently under development. It will be available soon.

**Comment by hbursk** [comment]
What's the status on this request? Would be helpful to be able to export all feedback, or feedback for a particular tag.

**Comment by passsy** [comment]
This feature has been released. You can now export your feedback in the Settings

<img width="1287" alt="Screen-Shot-2022-08-25-14-18-04 68" src="https://user-images.githubusercontent.com/1096485/186662352-33df467a-81e9-4e18-a03e-87240ec4c7f8.png">
