### ISSUE TITLE
Update Wiredash documentation to null-safety

### ISSUE THREAD

**Issue by zyllus17** [wiredashio/wiredash-sdk#150]
In the [Launching the Feedback Flow](https://docs.wiredash.io/guide/#launching-the-feedback-flow) part of documentation, it needs to be updated with null-safety by adding !(bang) operator after `context`.

**Non Null Safe**
```dart
onPressed: () => Wiredash.of(context).show(),
```
**Null safe**
```dart
onPressed: () => Wiredash.of(context)!.show(),
```
Same needs to be done in [Wiredash package documentation](https://pub.dev/packages/wiredash#-getting-started)

I am not raising a PR for the documentation as its a minor update.

**Comment by passsy** [comment]
The documentation has been fully updated.

https://docs.wiredash.io/
