### ISSUE TITLE
userId not shown in console anymore

### ISSUE THREAD

**Issue by saibotma** [wiredashio/wiredash-sdk#152]
I can not find the userId set according to https://docs.wiredash.io/configuration/properties/#user-properties on the Wiredash console anymore. 
I can find it when I look at the raw JSON response in the developer tools though.

**Comment by passsy** [comment]
Sorry for the late reply. That issue has been resolved for quite a while. THe user id and user email is visible on every feedback (when provided) 

![Screen-Shot-2023-11-29-15-53-32 07](https://github.com/wiredashio/wiredash-sdk/assets/1096485/a87741db-352d-4a67-b43d-30c2570e8627)
