### ISSUE TITLE
Changelog on pub.dev is weird formatted

### ISSUE THREAD

**Issue by nilsreichardt** [wiredashio/wiredash-sdk#156]
![image](https://user-images.githubusercontent.com/24459435/138452642-5ec0f616-fa57-41bf-9cd2-7d155d39e36d.png)

**Comment by nilsreichardt** [comment]
Could this be, because version `0.6.2` has no title? https://github.com/wiredashio/wiredash-sdk/blob/84f136029b42ea907a61e574fbd371cf654f3dd3/CHANGELOG.md?plain=1#L8

**Comment by flschweiger** [comment]
This will probably be fixed with the release of 1.0 😉

**Comment by passsy** [comment]
@nilsreichardt Because all others have a title! 

https://github.com/dart-lang/pub-dev/blob/1bdcb7ade75c9f830f419a2d0b0c8d98071ba217/app/lib/shared/markdown.dart#L333-L348
