### ISSUE TITLE
3rd Party Integration: Notion

### ISSUE THREAD

**Issue by hecker** [wiredashio/wiredash-sdk#157]
A few months ago [Notion](https://notion.so) published their Open API. It would be a huge improvement if you could, additionally to Slack, implement the Notion API into Wiredash. Would be a real game changer! 💫

**Comment by passsy** [comment]
You can now connect all your favorite tools via Zapier, including Notion

![zapier](https://docs.wiredash.io/images/zapier-dialog.png)

Checkout the docs https://docs.wiredash.io/integrations/zapier/
