### ISSUE TITLE
Widget is disposed when TextField is clicked

### ISSUE THREAD

**Issue by masfour7** [wiredashio/wiredash-sdk#158]
When I click on a TextField in one of the widgets in my app, the dispose method gets called and the keyboard is dismissed by itself. This only happens when I use the Wiredash widget. 

Do you have any idea why this might be happening?

**Comment by cenkingunlugu** [comment]
I have the same problem for a long time. I had to remove wiredash because of this bug.

**Comment by passsy** [comment]
That might be related to https://github.com/flutter/flutter/issues/94249. Do you have multiple navigators in your app?

**Comment by cenkingunlugu** [comment]
> That might be related to [flutter/flutter#94249](https://github.com/flutter/flutter/issues/94249). Do you have multiple navigators in your app?

Nope. I have a single navigator.

**Comment by MrEdgarsz** [comment]
I have the same problem in my app. Were you able to find some solution @masfour7  @cenkingunlugu?

**Comment by cenkingunlugu** [comment]
> I have the same problem in my app. Were you able to find some solution @masfour7 @cenkingunlugu?

No. Unfortunately, I had to remove wiredash from my app as adding text is the key functionality of my app and wiredash breaks it. Wish they will fix it someday.

**Comment by MrEdgarsz** [comment]
The new alpha version seems to fix the issue. Possibly something that caused this bug was removed/changed?

**Comment by passsy** [comment]
This does not happen anymore with Wiredash 1.0.0. Please update :)
