### ISSUE TITLE
[Proposal] Option Customization

### ISSUE THREAD

**Issue by AtaTrkgl** [wiredashio/wiredash-sdk#18]
I only want the "send feedback" button to be shown however we can't hide buttons. An option to customize which buttons will be shown would be great.

**Comment by flschweiger** [comment]
Hey @AtaTrkgl, thanks for your feedback! Which buttons would you like to hide? The different feedback types (e.g. bug / improvement / praise)?

**Comment by AtaTrkgl** [comment]
improvement button in my case. But the suggestion is general, being able to hide certain feedback types would be a nice addition

**Comment by Nash0x7E2** [comment]
Proposal:
```dart
WiredashOptionsData({
  showBugFeedback: true, 
  showPraiseFeedback: true,
  showFeatureRequest: true, 
});
```
Would this fit your needs @AtaTrkgl ? Adding these options to `WiredashOptionsData` would allow users to customize which options are shown to the user.

**Comment by AtaTrkgl** [comment]
Love it
