### ISSUE TITLE
Feedback was sent twice

### ISSUE THREAD

**Issue by ciriousjoker** [wiredashio/wiredash-sdk#186]
User also painted on the screenshot identically, so it's impossible that he sent it twice manually.

Perhaps Wiredash retries sending it if it didn't work, which could lead to it being sent twice?

Only happened once though and no big deal.

**Comment by passsy** [comment]
Hey Philipp,

Thanks for bringing this up. We can confirm that the feedback was actually sent multiple times.

We identified one issue that could cause this in our backend and one in the SDK (see above). We'll keep an eye on that in the future 👁

If possible, update to the latest (preview) [v1.0.0-alpha.6](https://github.com/wiredashio/wiredash-sdk/releases/tag/v1.0.0-alpha.6) release of the SDK, including the new fix.

**Comment by ciriousjoker** [comment]
We'll try to update to 1.0.0 for our next release. Do you consider alpha.6 ready for production? How long will it take until it is?

**Comment by passsy** [comment]
We're not far away from stable. Apps are already shipping with the alpha.

Go for it, if you encounter any problems we're here to help 😉
