### ISSUE TITLE
Can't see screenshots from user

### ISSUE THREAD

**Issue by eggnstone** [wiredashio/wiredash-sdk#190]
Using `wiredash: ^0.7.0+1`

I submitted a feedback and see it in the console but no screenshot visible although I saved and submitted it.
https://console.wiredash.io/project/remotetravel-t1jrqe5/feedback/6221ff9288c59f0f7b5c6003

**Comment by nouman-shoaib** [comment]
I am having the same issue, even though I am using a paid version.

**Comment by flschweiger** [comment]
We're looking into that, will get back to you asap!

**Comment by flschweiger** [comment]
Could you please retry submitting a screenshot, the issue should be resolved 🙂 Also make sure to check out our new SDK which is currently in alpha: https://pub.dev/packages/wiredash/versions/1.0.0-alpha.6

Sorry for the inconvenience, let us know if you have any other questions!
