### ISSUE TITLE
[Feature request] Make email template configurable 

### ISSUE THREAD

**Issue by luckyhandler** [wiredashio/wiredash-sdk#204]
We use a third party provider as support tool and have configured automatic response mails in this tool. When forwarding the feedback from Wiredash to our support mail a ticket is created and the provider sends an automatic reply to the user.

Unfortunately, the mail by Wiredash contains the link to the Wiredash dashboard which cannot be accessed by the user but it's still not cool as the user might ask hin/herself what the button is for anyway.

It would be great if one could configure the email template when forwarding the feedback.

**Comment by passsy** [comment]
Thanks Nino for your feedback!

The emails of the consoles' email integration are not designed to be forwarded to the users of your app.

Instead, I recommend checking out the [zapier](https://zapier.com/) integration. It allows you to forward incoming feedback to any 3rd party service you want. You could connect it directly to your support provider or pipe it through your own mail service where you can create your own template.

**Comment by luckyhandler** [comment]
Thanks for the quick feedback! will check that out
