### ISSUE TITLE
Locale doesn't seem to have an effect

### ISSUE THREAD

**Issue by SylvainLosey** [wiredashio/wiredash-sdk#206]
Hello,

I just installed the latest beta version on an app of mine ([1.0.0-beta.1](https://pub.dev/packages/wiredash/versions/1.0.0-beta.1)). My app is only available in french so I wanted to force the locale to 'fr', but it doesn't seem to work.

<img width="1664" alt="Screenshot 2022-05-13 at 13 53 53" src="https://user-images.githubusercontent.com/35432469/168278789-a98bb7f2-6a9b-4cdb-a04f-f0fc08f5c0a9.png">

Is this a bug or am I doing something wrong ?

**Comment by passsy** [comment]
Hey! Thanks for letting us know. This is now fixed in `1.0.0`.

Unfortunately, we don't yet support french natively, but you can add it yourself. Follow the documentation https://docs.wiredash.io/sdk/localization/#add-support-for-new-languages
