### ISSUE TITLE
Black screen issue when opening app

### ISSUE THREAD

**Issue by zyllus17** [wiredashio/wiredash-sdk#208]
Sometimes when I try to open the app, I get a black screen error. 
I am using `wiredash: 1.0.0-alpha.6` . Please fix it.

**Comment by flschweiger** [comment]
Hey @zyllus17, thanks for reaching out! Have you tried our [1.0.0-beta.2](https://pub.dev/packages/wiredash/versions/1.0.0-beta.2)? Wiredash should normally not affect the behaviour of a properly architected Flutter app - could you give us a little more info on how your widget tree looks like? Warm greetings from Germany!

**Comment by passsy** [comment]
Hey @zyllus17, are you still getting this error?

**Comment by zyllus17** [comment]
No, it was a bug in my app with a builder function. It was not related to wiredash. Sorry for such a late reply, I forgot to inform you.
