### ISSUE TITLE
Wiredash Api responds with error 400 for valid emails with whitespace after them

### ISSUE THREAD

**Issue by ciriousjoker** [wiredashio/wiredash-sdk#210]
Steps to reproduce:
- Send feedback
- Add valid email
- Add space at the end
- Press send

The UI indicates no issue, but the error can be seen in Crashlytics that Wiredash api responds with error 400.

This could easily be fixed for all Wiredash versions by `.trim()`ing the incoming email.

Note that we're still running on the old 0.7 version of the sdk because we couldn't get the v1 alpha to work properly and had no time yet to try out the beta.

**Comment by passsy** [comment]
This has been resolved in 1.0.0, which is now stable
