### ISSUE TITLE
Locale should fallback to language-only if language_Country provided has no explicit match

### ISSUE THREAD

**Issue by mdrideout** [wiredashio/wiredash-sdk#220]
Our app supports a list of locales that the user can switch in the settings at any time. All of our locales support both the language and country parameters.

The Wiredash local parameter does not work if the country parameter is specified, however, it does work if only the language is specified.

Example: **This was tested with** a Locale() of `de_DE` for the currently supported German language in 1.0.0-beta5

**not working**
```dart
options: WiredashOptionsData(
              locale: _locale,
            ),
```

**working**
```dart
options: WiredashOptionsData(
              // Locale in wiredash does not support defining a country code as of 1.0.0-beta5, so derive from just the language code
              locale: (_locale == null) ? null : Locale.fromSubtags(languageCode: _locale.languageCode),
            ),
```

Wiredash should be able to handle both situations by falling back to language code only if an unsupported language_Country combination is provided.

**Comment by passsy** [comment]
Fixed in 1.0.0
