### ISSUE TITLE
Use two different fonts for headlines and body

### ISSUE THREAD

**Issue by ciriousjoker** [wiredashio/wiredash-sdk#222]
We use Bebas Neue Pro for the headlines and Roboto for body text. Would it be possible to specify these in the theme in a future version? For now we'll release our next app version with Roboto for everything (and v1.0.0-beta.5 of Wiredash).

@passsy Are you open to PRs in this regard?

**Comment by passsy** [comment]
This should now be possible with the `v1.0.0` release. Check out `WiredashThemeData.textTheme` and let me know if it covers all your needs.
