### ISSUE TITLE
Open/close animation is a bit janky

### ISSUE THREAD

**Issue by ciriousjoker** [wiredashio/wiredash-sdk#225]
First launch is pretty bad, but that can be fixed by precompiling the shaders on real devices.

However, even when it's warmed up, the framerate still isn't great.
After looking at performance traces and the code I found this:

https://github.com/wiredashio/wiredash-sdk/blob/5c2164e3d3c99c34e5ca6adc6dd1023fe0df81be/lib/src/core/widgets/backdrop/wiredash_backdrop.dart#L720-L722

Animated clipping with `antiAliasWithSaveLayer` must be a nightmare for Skia. Why isn't it enough to use basic `antiAlias` clipping here?

Even if it has to be `antiAliasWithSaveLayer`, it would probably still be enough to use `antiAlias` (or even `hardEdge` for that matter!) during the animation and only switch back once the animation is done.

**Comment by passsy** [comment]
Thanks for bringing this up!

Performance was addressed in #231. I did not see an effect removing `antiAliasWithSaveLayer`, but the other improvements should result in smooth 60fps now.
