### ISSUE TITLE
Grey screen on release

### ISSUE THREAD

**Issue by woutervanwijk** [wiredashio/wiredash-sdk#234]
When upgrading from 0.7.1 to 1.0.0, I get a grey screen when opening WD. Not in debug mode, it's all ok, but in release only. I followed the instructions

**Comment by passsy** [comment]
Thanks for letting us know!
A gray screen unusually means some Widget crashed. Can you check the device log for a stacktrace?
On which platform are you seeing the crash?

**Comment by passsy** [comment]
Please try to `1.1.0` release. It should be fixed :)

**Comment by woutervanwijk** [comment]
Works great!
