### ISSUE TITLE
l18n: Support for Spanish (es) 🇪🇸

### ISSUE THREAD

**Issue by passsy** [wiredashio/wiredash-sdk#236]
Translate Wiredash to Spanish.

Unfortunately, we aren't fluent in Spanish and would like a native speaker to help us out.

Please follow the [instructions](https://docs.wiredash.io/sdk/localization/#add-support-for-new-languages) on how to contribute your locale to Wiredash 💙

**Comment by passsy** [comment]
@orkwizard?

**Comment by jamesblasco** [comment]
You can assign this to me! I will take a look into it in the next few days

**Comment by orkwizard** [comment]
Would Love to help but on vacations until aug 16 .. will look on it that
date
