### ISSUE TITLE
l18n: Support for Polish (pl) 🇵🇱

### ISSUE THREAD

**Issue by passsy** [wiredashio/wiredash-sdk#238]
Translate Wiredash to Polish.

Unfortunately, we aren't fluent in Polish and would like a native speaker to help us out.

Please follow the [instructions](https://docs.wiredash.io/sdk/localization/#add-support-for-new-languages) on how to contribute your locale to Wiredash 💙

**Comment by orestesgaolin** [comment]
I can help ✋
