### ISSUE TITLE
l18n: Support for Portuguese (pt) 🇵🇹

### ISSUE THREAD

**Issue by passsy** [wiredashio/wiredash-sdk#240]
Translate Wiredash to Portuguese.

Unfortunately, we aren't fluent in Portuguese and would like a native speaker to help us out.

Please follow the [instructions](https://docs.wiredash.io/sdk/localization/#add-support-for-new-languages) on how to contribute your locale to Wiredash 💙

**Comment by passsy** [comment]
@KyleKun?

**Comment by KyleKun** [comment]
Hi @passsy, sure thing!
But actually, I can help with Brazilian Portuguese, is that okay?
