### ISSUE TITLE
Email metadata isn't loaded properly the first time

### ISSUE THREAD

**Issue by ciriousjoker** [wiredashio/wiredash-sdk#243]
**Describe the bug**
Steps to reproduce:
1. Open app (first open or restart, not hot reload)
2. Send feedback
3. On the email step, the email is missing
4. Submit the feedback or discard it (doesn't matter, as long as you trigger the `collectMetadata` callback, for example by clicking "show details")
5. Send another feedback
6. Email field now contains the correct email

**Stacktrace**
N/A

**Wiredash SDK Info**
1.1.0

**Flutter SDK**
7.0.4

**Screenshots**
N/A

**Comment by passsy** [comment]
Are you providing the email with `collectMetadata`?

**Comment by ciriousjoker** [comment]
Yes. In the steps above, at no point do you have to manually enter an email, so collectMetadata provides that data once asked. It just seems like it's asked too late in the process.

Additionally, custom metadata is always passed. However, if we skip the email step, then even though custom data is passed (ie we can be sure that Wiredash has called collectMetadata and knows about the email), the email isn't passed to us. This seems like a bug but it might be intentional.

Either way, we'd like to skip the email step to reduce friction, but still get their email via collectMetadata. It works with their user id already, just not with the email. We can obviously get their email by looking up the uid but that's annoying and if this is a wontfix then I'd definitely have to build the semi-planned slack bot to look up user data based on uid to simplify support requests

**Comment by S-ecki** [comment]
I am facing this exact issue with the latest SDK version. Any updates @passsy?

**Comment by matthewwong525** [comment]
I'm encountering the same issue as well!

**Comment by passsy** [comment]
This issue has been resolved in wiredash [1.7](https://github.com/wiredashio/wiredash-sdk/releases/tag/v1.7.0)
