### ISSUE TITLE
No-reply

### ISSUE THREAD

**Issue by woutervanwijk** [wiredashio/wiredash-sdk#245]
When I get an email from wiredash, the reply address is no-reply@wiredash.io. When I reply via email, I get a bounce off course. This while the user (often) filled in a good email. 

**Describe the solution you'd like**
Add the users address as the reply-to address 

**Describe alternatives you've considered**
copy the user email

**Comment by flschweiger** [comment]
This feature has been added a while back. When a user has provided an email, it will be used as the replyTo in the email integration.

**Comment by gibahjoe** [comment]
Hi, is there a way to customise the email sent to the user when replying to email? Right now it has a button that says "open in console" and since users dont have access to that, its pointless.
