### ISSUE TITLE
[Proposal] Remove hardcode api url

### ISSUE THREAD

**Issue by stefandevo** [wiredashio/wiredash-sdk#25]
Hi, I saw 
https://github.com/wiredashio/wiredash-sdk/blob/master/lib/src/common/network/api_client.dart#L13

I think it would be great that this is a property that can be set; I was thinking of test scenario's where you could use a mock api, localhost, whatever

**Comment by Nash0x7E2** [comment]
Thank you for raising this issue. I think this is something we can pass into the widget as part of the configuration.

**Comment by Nash0x7E2** [comment]
After discussing this with the team, we've decided to revisit this at a later phase.

**Comment by stefandevo** [comment]
Okay too bad (it is just 1 property though)
