### ISSUE TITLE
No top padding on a Google Pixel 4a

### ISSUE THREAD

**Issue by nilsreichardt** [wiredashio/wiredash-sdk#254]
**Describe the bug**
There is no top padding on a Google Pixel 4a (see screenshot).

**Wiredash SDK Info**
Just used the localization example: https://github.com/wiredashio/wiredash-sdk/tree/stable/examples/localization

**Flutter SDK**
```
Flutter 3.3.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ffccd96b62 (8 days ago) • 2022-08-29 17:28:57 -0700
Engine • revision 5e9e0e0aa8
Tools • Dart 2.18.0 • DevTools 2.15.0
```

**Screenshots**

![telegram-cloud-photo-size-2-5242486220674678045-y](https://user-images.githubusercontent.com/24459435/188850979-be389230-23cd-4764-a754-06879be11464.jpg)

**Comment by passsy** [comment]
This issue has been resolved in wiredash [1.7](https://github.com/wiredashio/wiredash-sdk/releases/tag/v1.7.0)
