### ISSUE TITLE
Transparent layer above bottomNavigationBar

### ISSUE THREAD

**Issue by rmadridm** [wiredashio/wiredash-sdk#26]
We are currently testing the Wiredash package to implement it in our application, very good work by the way, but apparently there is some transparent layer that is positioned above the "bottomNavigationBar" and does not possible to tap on the button lower left side, this only happens to me when I set the property "showDebugFloatingEntryPoint: true", to show from the start the 
Wiredash dragabble FAB:

```
options: WiredashOptionsData (
  showDebugFloatingEntryPoint: true,
),
```

Any suggestion?

Thanks in advance for your help.

**Comment by Nash0x7E2** [comment]
Thank you for reporting this, we will try to reproduce this and get back to you.

**Comment by adiltirur** [comment]
+1
