### ISSUE TITLE
bug after update 1.5.0

### ISSUE THREAD

**Issue by elmoagusti2** [wiredashio/wiredash-sdk#260]
**Describe the bug**
hi,  I'm having trouble updating to v1.5.0, before my code was like this and it worked fine on v0.7.1, my code and screenshot are included below

**Stacktrace**
_What's the stacktrace?_
In browsers, check the `Console`.

**Wiredash SDK Info**
1.5.0
 android & ios

**Flutter SDK**
3.6.6

**Screenshots**
code before update, work
<img width="654" alt="Screenshot 2022-12-09 at 21 10 08" src="https://user-images.githubusercontent.com/117245037/206720744-d3d81661-06f8-4808-8a96-b1ff47390063.png">
<img width="339" alt="Screenshot 2022-12-09 at 21 11 17" src="https://user-images.githubusercontent.com/117245037/206720978-637dee6a-2434-4ef3-80e3-f8555fefa2d8.png">

code after update, not work
<img width="578" alt="Screenshot 2022-12-09 at 21 15 28" src="https://user-images.githubusercontent.com/117245037/206721728-272a1635-d15a-4a05-a8bb-c0054077fb54.png">
<img width="341" alt="Screenshot 2022-12-09 at 21 17 32" src="https://user-images.githubusercontent.com/117245037/206722083-50bad33d-14d2-42fd-ae01-90d0ae70610c.png">

Stacktrace
<img width="714" alt="Screenshot 2022-12-09 at 21 23 59" src="https://user-images.githubusercontent.com/117245037/206723452-f91a3bf9-faee-4692-9a5a-448893553ae5.png">

**Comment by passsy** [comment]
Thanks for the report. The same issue was reported before. Please check out https://github.com/wiredashio/wiredash-sdk/issues/252 and follow the instructions there.

Please let us know if it resolves your issue ✌️

**Comment by elmoagusti2** [comment]
terimakasih banyak, problemnya sudah teratasi.
