### ISSUE TITLE
Another exception was thrown: TypeError: Cannot read properties of undefined (reading 'then')

### ISSUE THREAD

**Issue by christianjensen2903** [wiredashio/wiredash-sdk#264]
**Describe the bug**
I tried to follow the tutorial by wrapping the materialApp in a Wiredash Widget. And then in the scaffold a floating action button calling Wiredash.of(context).show();. This however results in a error

**Stacktrace**
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following UnsupportedError was thrown building DefaultSelectionStyle:
Unsupported operation: Cannot modify unmodifiable map
The relevant error-causing widget was:
Wiredash
main.dart:43
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 265:5          _set
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:10  callMethod
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 435:5   dsend
packages/intl/date_symbol_data_custom.dart 35:19                                  initializeDateFormattingCustom
packages/flutter_localizations/src/utils/date_localizations.dart 23:33            <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13          forEach

**Wiredash SDK Info**
The Flutter sdk

**Flutter SDK**
3.7.1

**Screenshots**
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/15799390/223488638-a1c57536-9c39-4658-adf5-9a2a5e64765f.png">

**Comment by passsy** [comment]
Hey, thanks for reporting.

This is a known issue with `initializeDateFormatting()` (https://github.com/flutter/flutter/issues/70040), you can fix this as described in https://github.com/wiredashio/wiredash-sdk/issues/252#issuecomment-1235621621
