### ISSUE TITLE
Wiredash sdk is not compatible with Flutter 3.10

### ISSUE THREAD

**Issue by BirjuVachhani** [wiredashio/wiredash-sdk#277]
**Describe the bug**
Wiredash sdk is not compatible with Flutter 3.10. Dependency resolution fails due to incompatible version with `flutter_localization` package.

**Stacktrace**
```
Because no versions of wiredash match >1.6.0 <2.0.0 and wiredash 1.6.0 depends on flutter_localizations from sdk, wiredash ^1.6.0 requires flutter_localizations from sdk.
And because every version of flutter_localizations from sdk depends on intl 0.18.0, wiredash ^1.6.0 requires intl 0.18.0.
So, because codelessly depends on both intl 0.17.0 and wiredash ^1.6.0, version solving failed.
```

**Wiredash SDK Info**
```
wiredash: ^1.6.0
```

**Flutter SDK**
Flutter v3.10.0

**Screenshots**
![image](https://github.com/wiredashio/wiredash-sdk/assets/20423471/f564ab90-339c-4cc2-ab79-cd031b833b19)

**Comment by passsy** [comment]
Thanks for reporting. For now, use a `dependency_override`

```
dependency_overrides:
  intl: ^0.18.0
```

The update will follow shortly

**Comment by BirjuVachhani** [comment]
Seems like wiredash constraints are fine but its the firebase_auth_web that has a hard version conflict that creates issues with Flutter SDK and wiredash. Overriding dependency didn't work for me. I had to fork firebase_auth_web and update the version there.

**Comment by passsy** [comment]
I can confirm, this is not wiredash related. Wiredash uses whatever version of `flutter_localizations` is provided by the flutter SDK 

https://github.com/wiredashio/wiredash-sdk/blob/18d5828eaf875065fe1a3d11d678100069ae95a0/pubspec.yaml#L18-L19
