### ISSUE TITLE
How to redirect the app to a specific screen after submitting feedback

### ISSUE THREAD

**Issue by poojadev** [wiredashio/wiredash-sdk#282]
Hello, we are using Wiredash in our application for gathering feedback. but facing one issue after submitting feedback, Wiredash always redirects it to the home page rather than redirecting to a specific page. Is there any solution? How can we redirect it to a specific screen after submitting feedback.
i.e., I'm submitting feedback from the profile page, but Wiredash always redirects it to the main home page.

**Comment by passsy** [comment]
Wiredash doesn't navigate at all and does not redirect to the home page.

It seems like you lose the application state at some point, resetting your Navigator and thus land on the home page. There could be a million reasons why it is happening.

One common mistake is to initialize some things in `didChangeDependencies`. Especially, high up in the widget tree, devs often expect `didChangeDependencies` to be called only once. But it is called again when wiredash opens/closes.

There is currently no callback when a user leaves the feedback flow. But is that actually what you want or do you only want to stay on the current page?

**Comment by poojadev** [comment]
Yes I  only want to stay on the current page  like router.pop() and I'm using auto_route package for routing.

**Comment by passsy** [comment]
Assuming you copy-pasted the sample from the readme:

```dart
// assuing this is the root widget of your App                 
class App extends StatelessWidget {            
  // make sure you don't initiate your router                
  // inside of the build function.                
  final _appRouter = AppRouter();            
            
  @override            
  Widget build(BuildContext context){            
    return MaterialApp.router(            
      routerConfig: _appRouter.config(),         
    );            
  }            
}    
```

You will lose the state of the `_appRouter` whenever the App rebuilds. (That's what's happening when Wiredash opens/closes).

Make it a `StatefulWidget` instead, and save `_appRouter` in your state

**Comment by poojadev** [comment]
Yes I have copy pasted the sample from the readme thank you for your suggestion. I'll try the above code.

**Comment by poojadev** [comment]
```dart
  return Wiredash(
        options: WiredashOptionsData(
          localizationDelegate: const CustomWiredashTranslations(),
        ),
        projectId: '',
        secret: '',
        child: MaterialApp.router(
          routerConfig: _appRouter.config(
            navigatorObservers: () => [
              SentryNavigatorObserver(),
            ],
          ),
``` 
Hi we are already using  StatefulWidgets and saving stated in  _appRouter.  Still when i submit feedback it re-builds and redirects to main page.

**Comment by passsy** [comment]
Then you have to figure out why `Navigator` gets disposed, or who's navigating to `home`. Try setting breakpoints and try to find the root cause.

You could also try playing around with global keys. Set one to `Wiredash`, one to `MaterialApp.router` and so on. It might fix it but that is not solving the root cause. You might run into other problems.

There's nothing I can help you with from here, sorry. The error is not reproducible in an example. It is a bug somewhere in your codebase.
