### ISSUE TITLE
The PSOptions frequency parameter works incorrectly.

### ISSUE THREAD

**Issue by Hamittrpn** [wiredashio/wiredash-sdk#286]
I am using the following values in ps options for showing score;
- Frequency : Duration(day:300)
- InitialDelay: Duration.Zero
- MinimumAppStarts : 0

This is how I use it so that if the user votes, they can vote the next time after 300 days. However, the promote score screen does not appear at the start of the application and it says that it will start after 300 days due to the frequency.

How can i solve this?

**Comment by passsy** [comment]
Hey, thanks for contacting us. I would say it is working as expected.

In the very first period, Wiredash [randomizes the date of the first survey](https://github.com/wiredashio/wiredash-sdk/blob/7520e0d6b583319f662ab7c4105a0e4a4d9f6029/test/ps/ps_trigger_test.dart#L105-L143C6) within the frequency (300 days). This means, your users do not immediately get to see the survey but only guaranteed within the 300 days. Some might get it at day 1, but others at day 299.

This guarantees that you get continuous updates to your promoter score, and not a huge number of responses after integrating wiredash and then nothing for a long time for your long-term customers.

If you really want to force showing the survey call this method: 

```dart
WidgetsBinding.instance.addPostFrameCallback((_) {
  Wiredash.of(context).showPromoterSurvey(force: true);
});
```

Be warned, once all your users got the survey, they are not prompted again within the next period (300 days). You might get good responses at first but for the longest time, you'll end up only with responses from new users.
