### ISSUE TITLE
Preserve route history

### ISSUE THREAD

**Issue by danielkauffmann** [wiredashio/wiredash-sdk#287]
**Is your feature request related to a problem? Please describe.**
Every time I use `Wiredash.of(context).show()` and return to the app, the history of previous routes gets lost. Even the screen the user was on before opening Wiredash also rebuilds during the opening of the feedback top panel.

**Describe the solution you'd like**
I would like the route history to be preserved during user feedbacks.

**Describe alternatives you've considered**
I tried wrapping the `Wiredash` widget before and after `MaterialApp.router` but it didn't changed the behavior described before.

**Additional context**
I'm using [AutoRoute](https://pub.dev/packages/auto_route) for my app routing.

**Comment by passsy** [comment]
This is not an issue of wiredash, it doesn't change anything. The issue most likely lies in the fact, that you lose the router state, because you hold it in a stateless widget.

See this [issue](https://github.com/wiredashio/wiredash-sdk/issues/262#issuecomment-1418134832) how to resolve it

**Comment by danielkauffmann** [comment]
> This is not an issue of wiredash, it doesn't change anything. The issue most likely lies in the fact, that you lose the router state, because you hold it in a stateless widget.
> 
> See this [issue](https://github.com/wiredashio/wiredash-sdk/issues/262#issuecomment-1418134832) how to resolve it

Just changed to StatefulWidget and it still rebuilding when open Wiredash.

My current app widget
```dart

class App extends StatefulWidget {
  const App({super.key});

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  // Singletons
  final theme = getIt<AppTheme>();
  final router = getIt<AppRouter>();
  final lastThemeMode = getIt<AdaptiveThemeMode>();

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        // BlocProviders...
      ],
      child: ResponsiveSizer(
        builder: (context, orientation, screenType) {
          return AdaptiveTheme(
            light: theme.theme(),
            dark: theme.darkTheme(),
            initial: lastThemeMode,
            builder: (theme, darkTheme) {
              return Wiredash(
                // ...
                child: MaterialApp.router(
                  theme: theme,
                  darkTheme: darkTheme,
                  routerConfig: router.config(),
                  supportedLocales: AppLocalizations.supportedLocales,
                  localizationsDelegates: AppLocalizations.localizationsDelegates,
                  debugShowCheckedModeBanner: false,
                  builder: FToastBuilder(),
                ),
              );
            },
          );
        },
      ),
    );
  }
}
```

Am I missing something?

**Comment by danielkauffmann** [comment]
Hey @passsy, do you have any idea what could prevent the router to preserve the state?

**Comment by danielkauffmann** [comment]
See #289 for more details, closing this discussion.
