### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by robinbonnes** [wiredashio/wiredash-sdk#288]
Some translations are missing, specifically:

https://github.com/wiredashio/wiredash-sdk/blob/5ac0b9dd2658fbafcab3bf822730f7168a729fb6/lib/src/feedback/feedback_backdrop.dart#L190

https://github.com/wiredashio/wiredash-sdk/blob/5ac0b9dd2658fbafcab3bf822730f7168a729fb6/lib/src/feedback/steps/step_6_submit.dart#L111C41-L111C41

**Comment by passsy** [comment]
Thanks for the report! The first one is fixed in wiredash 1.7.4

The second one isn't, a new design is landing soonish with new copy texts
