### ISSUE TITLE
Wiredash app on play store

### ISSUE THREAD

**Issue by varadkulk** [wiredashio/wiredash-sdk#29]
It is very hard to keep track of feedbacks on the go as it is only on web. So it would be great if we have an app on our phones.

**Comment by Nash0x7E2** [comment]
Thank you for your suggestion. 

At this time we don't have any plans for a companion app however this may change in the future.

**Comment by passsy** [comment]
Agree! As first step, I'd be happy if the console would be mobile optimized.

**Comment by Nash0x7E2** [comment]
A mobile-optimized console is something we would like to do in the near future! In the meantime, our primary focus is polishing the existing features and finishing up the remaining critical components.
