### ISSUE TITLE
Fails to submit feedback with getAll error.

### ISSUE THREAD

**Issue by Mmisiek** [wiredashio/wiredash-sdk#290]
I/flutter (27252): Submitting feedback
I/flutter (27252): MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
I/flutter (27252):
I/flutter (27252): MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
I/flutter (27252):
D/EGL_emulation(27252): app_time_stats: avg=71.41ms min=15.41ms max=838.22ms count=15

════════ Exception caught by wiredash ══════════════════════════════════════════
The following MissingPluginException was thrown:
MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

When the exception was thrown, this was the stack
Feedback submission failed
════════════════════════════════════════════════════════════════════════════════

**Comment by passsy** [comment]
Which Flutter version are you using, and what's your `pubspec.lock`?
Which platform are you running this code on?

Usually, this kind of issue is resolved with `flutter pub upgrade`. You're shared_preferences version might be incompatible with your current Flutter version.

**Comment by Mmisiek** [comment]
The flutter pub upgrade helped. Thank you
