### ISSUE TITLE
Flutter 3.13: No named parameter with the name 'isAlwaysShown'.

### ISSUE THREAD

**Issue by Albert-Jan** [wiredashio/wiredash-sdk#291]
**Stacktrace**
`pub.dev/wiredash-1.7.2/lib/src/core/widgets/backdrop/step_page_scaffold.dart:340:9: Error: No named parameter with the name 'isAlwaysShown'.`

**Wiredash SDK Info**
1.7.2 on iOS

**Flutter SDK**
3.13.0

**Comment by cody-fjorge** [comment]
Reverting to Flutter 3.10.6 will solve the issue. The Scrollbar implementation needs to be updated for the plugin to work on the latest stable channel of flutter (3.13.0).
<img width="586" alt="Screen Shot 2023-08-16 at 4 36 13 PM" src="https://github.com/wiredashio/wiredash-sdk/assets/65675656/933f82da-55a9-47d8-833b-e7585ddcf80e">

**Comment by passsy** [comment]
Fix has been released [`1.7.3`](https://github.com/wiredashio/wiredash-sdk/releases/tag/v1.7.3)
