### ISSUE TITLE
Weird colors

### ISSUE THREAD

**Issue by kareldb** [wiredashio/wiredash-sdk#294]
**Describe the bug**
When I trigger wiredash, the colors are weird.

**Stacktrace**
_What's the stacktrace?_
In browsers, check the `Console`.

**Wiredash SDK Info**
latest

**Flutter SDK**
latest

**Screenshots**

<img width="453" alt="wiredash" src="https://github.com/wiredashio/wiredash-sdk/assets/83468355/13f3d9ca-3648-4850-9252-1db24d653b1e">

**Comment by passsy** [comment]
Thanks for reaching it, that's an interesting color combination 😁 

The [automatic theming](https://github.com/wiredashio/wiredash-sdk/blob/32ffd443032c22b9312da38a24ffc06b5cdc766d/lib/src/core/wiredash_controller.dart#L206-L242) picks the colors from your material theme. I assume you defined some red and yellow colors in your theme. Our automatic system might not look pleasant for all color combinations, like yours.

If you think we chose the wrong colors, provide your material theme so we can try to fix it.

I recommend you define your own colors. Checkout the documentation about [Theming](https://docs.wiredash.io/sdk/theming/)

**Comment by passsy** [comment]
Don't hesitate to reach out for more questions!

**Comment by kareldb** [comment]
Thanks! 
I don't use those material colors anywhre in the app.


I tried adding the custom styling example:

```
     theme: WiredashThemeData.fromColor(
        // Customize Brightness and Colors
        // Primary button color, step indicator, focused input border
        primaryColor: Colors.indigo,
        // Secondary button color (optional)
        secondaryColor: Colors.purple,
        brightness: Brightness.light,
      ).copyWith(
        // i.e. selected labels, buttons on cards, input border
        primaryContainerColor: Colors.black,
        textOnPrimaryContainerColor: Colors.black,

        // i.e. labels when not selected
        secondaryContainerColor: Colors.black,
        textOnSecondaryContainerColor: Colors.white,

        // the color behind the application, only visible when your app is
        // translucent
        appBackgroundColor: Colors.white,
        // The color of the "Return to app" bar
        appHandleBackgroundColor: Colors.blue[700],

        // The background gradient, top to bottom
        primaryBackgroundColor: Colors.white,
        secondaryBackgroundColor: Colors.white,

        errorColor: Colors.red,

        firstPenColor: Colors.yellow,
        secondPenColor: Colors.black,
        thirdPenColor: Color(0xffffebeb),
        fourthPenColor: Color(0xffced9e3),
      ),
```      

But it still looks really weird

<img width="420" alt="wd 2" src="https://github.com/wiredashio/wiredash-sdk/assets/83468355/d6110375-879d-42fe-9ddf-8f471455349c">

**Comment by passsy** [comment]
The theme you provided looks like this for me:

<img width="571" alt="Screen-Shot-2023-08-23-22-21-58 93" src="https://github.com/wiredashio/wiredash-sdk/assets/1096485/5726bc51-577b-4352-a22a-f72a4e3bf2e0">

I also can't tell where the yellow colors are coming from. It must be something in your code.

Is your app using any kind of shaders? It feels like some widget, above the `Wiredash` widget is screwing with the rendering. I recommend removing widgets until the app is basically a simple hello world example.
Can you reproduce it in one of the `/examples` or only in your app?
Are you also seeing it on other devices? You might have enabled some kind of color blindness mode

**Comment by passsy** [comment]
Can't reproduce
