### ISSUE TITLE
Mark feedback as resolved

### ISSUE THREAD

**Issue by passsy** [wiredashio/wiredash-sdk#3]
I'd love to mark feedback as closed/resolved/done so it doesn't show up in to console anymore. I receive plenty of feedback from my users and it's kind of hard to maintain all the feedback in a larger team.

**Comment by flschweiger** [comment]
It is now possible to close feedback but we should think about implementing a nicer way of displaying. For that I have opened https://github.com/wiredashio/wiredash-sdk/issues/13 - closing here :)
