### ISSUE TITLE
Add links to privacy policy and terms in the console

### ISSUE THREAD

**Issue by AndroidNils** [wiredashio/wiredash-sdk#30]
## Description
The only way to access the privacy policy and terms of service is to sign out and click "sign up". It would be much better to add a link to the privacy policy and terms of service in the console.

There is no link. Even not in the configurations.
![image](https://user-images.githubusercontent.com/24459435/83303950-40d9c480-a1fe-11ea-9c68-370820bcd3ef.png)

**Comment by flschweiger** [comment]
This is fixed in the new console since you can access the help pages directly from there 🙂
