### ISSUE TITLE
Console typo in report with scheenshots

### ISSUE THREAD

**Issue by IvanKozhemyakinWG** [wiredashio/wiredash-sdk#306]
Thare are multiple screenshots attached to this feedback.
Click onto them to skim through them.

^ This text is appeared if feedback contains any screenshots.
'Thare'

2 cents

P.S. You are doing incredible tool for feedback and bug reporting!
Looking forward for telegram integration feature

**Comment by passsy** [comment]
Hey Ivan, thanks for your feedback and your kind words!
The fix landed in the console :)
