### ISSUE TITLE
Integrations should also export NPS results

### ISSUE THREAD

**Issue by ciriousjoker** [wiredashio/wiredash-sdk#307]
**Is your feature request related to a problem? Please describe.**
We just started using the Net Promoter Survey feature and it's amazing.
However, unless we look into the Wiredash Console manually, the comments are essentially lost since we can't figure out how to transfer them into our CRM tool & Slack.

**Describe the solution you'd like**
Send the content of NPS comments to the email integration, ideally with some sort of keywords so we can automatically label them in our CRM.

**Describe alternatives you've considered**
- Zapier, but it doesn't work
- The Slack integration also doesn't have this feature
- Manually export via mimicked browser requests through our backend, but the functionality to export the results is "coming soon", ie not available

**Additional context**
If there's some sort of internal/beta webhook integration we could test, we'd love to try it out, feel free to enable it for our account.

**Comment by flschweiger** [comment]
Hey @ciriousjoker 👋  

Thanks for reaching out. We're looking into how we can add value through a custom email or Zapier integration. Probably something like a per day / week / month report which you can get via email. Also we'll be adding the possibility to export NPS shortly.

Would you mind shooting us an email to support@wiredash.io so we can follow up on this? I'm leaving this issue open for now until there's a working solution.

**Comment by passsy** [comment]
The promoter score, like the feedbacks, can now be exported in the console.

![Screen-Shot-2023-11-28-21-45-29 62](https://github.com/wiredashio/wiredash-sdk/assets/1096485/6bb31025-e77e-4b83-827f-f53d50d7fcdf)
