### ISSUE TITLE
Can't invite member with a .info domain

### ISSUE THREAD

**Issue by AndroidNils** [wiredashio/wiredash-sdk#31]
I tried to invite some team members. Our mail looks like this `name@sharezone.info`. Unfortunately Wiredash doesn't accept this email 😭
 
![image](https://user-images.githubusercontent.com/24459435/83308360-f741a780-a206-11ea-9798-84ff08f6f345.png)

**Comment by flschweiger** [comment]
Thanks, will have a look at this over the weekend 👍

**Comment by AndroidNils** [comment]
The same applies to the following endings (small selection): `capital`, `berlin`, `bayern`, `hamburg`, `koeln`, `party`, `club`, `band`, `live`, `hosting`, `technology`, `codes`, `shop`, `kaufen`, `discount`

**Comment by AndroidNils** [comment]
`nils+spam@sharezone.net` is also not possible :(

![image](https://user-images.githubusercontent.com/24459435/83309040-7e434f80-a208-11ea-95d1-012a7470d655.png)

**Comment by AndroidNils** [comment]
Maybe is this helpful: https://stackoverflow.com/questions/2049502/what-characters-are-allowed-in-an-email-address 😅✌️

**Comment by flschweiger** [comment]
Thanks, there was a mistake in the frontend email validation and this is fixed now 🎉
