### ISSUE TITLE
Stuck on Thanks Screen

### ISSUE THREAD

**Issue by pablojoii** [wiredashio/wiredash-sdk#310]
**Describe the bug**
After a few feedbacks given, it got stuck on the Thank you screen whenever Wiredash.show was called. Happened on iOS. Even going back to the app and calling it again, it was showing always the Thanks screen. Had to kill app to get it working again.

**Stacktrace**
Happened on release mode, no stack generated/available.

**Wiredash SDK Info**
1.7.5

**Flutter SDK**
Flutter 3.10.3 • channel unknown • unknown source
Framework • revision f92f44110e (6 months ago) • 2023-06-01 18:17:33 -0500
Engine • revision 2a3401c9bb
Tools • Dart 3.0.3 • DevTools 2.23.1
iOS 17

**Screenshots**
![image](https://github.com/wiredashio/wiredash-sdk/assets/146714305/c6f478c0-ada7-4ee2-bcfe-e0f8fa3734e7)

**Comment by passsy** [comment]
Thanks for the report!

The issue was hard to track down but I finally found it. Moving the app while submitting the feedback finally resulted in this state.
Fixed it, will be part of the next release
