### ISSUE TITLE
Automatically add screenshot on Wiredash.show()

### ISSUE THREAD

**Issue by pablojoii** [wiredashio/wiredash-sdk#312]
**Is your feature request related to a problem? Please describe.**
Automatically add screenshot on Wiredash.show(). We had people reporting feedbacks with no images, which made it really hard to get what was they talking. They told us they thought that activating the feedback would include automatically an image of the screen.

**Describe the solution you'd like**
Automatically do a screenshot on wiredash.show and let the reporter to remove in case they don't want to send it

**Comment by passsy** [comment]
Thanks for reporting! That should be doable 👍 

Duplicate #159
