### ISSUE TITLE
Linebreaks are lost

### ISSUE THREAD

**Issue by pablojoii** [wiredashio/wiredash-sdk#313]
**Describe the bug**
Quite simple: send a list 1 -.... \n, 2-... \n and see that linebreaks are dismissed.

**Screenshots**

Partial screenshot to avoid info going out.

![image](https://github.com/wiredashio/wiredash-sdk/assets/146714305/c732fc7a-0630-4147-9f03-6af71745c740)

**Comment by flschweiger** [comment]
Hey @pablojoii, thanks for reaching out! We've fixed that in the latest release ☑️

**Comment by pablojoii** [comment]
Hi, should I report a new bug? I can se the line breaks, thank, but longer lines are now going all the way out of the box, hahahha.

![image](https://github.com/wiredashio/wiredash-sdk/assets/146714305/6ad74faa-d8b8-45cf-9a2c-3d38216741d8)

**Comment by flschweiger** [comment]
Aarrrghh, CSS is hard 😅  No seriously, the problem should be solved now.

**Comment by pablojoii** [comment]
Hahahahhahan, it's really a pain. Used to be so simple: you had a table and content respected the table.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
