### ISSUE TITLE
GitHub Sign-In fails when no GitHub name is set

### ISSUE THREAD

**Issue by flschweiger** [wiredashio/wiredash-sdk#32]
For a small percentage the GitHub sign in does not work and we are currently investigating the issue. Google Sign in is not affected.

**Comment by leidig54** [comment]
I was unable to signup using my GitHub account. Google worked. Safari Version 13.1.1 (15609.2.9.1.2). Thanks for a great plugin.

**Comment by flschweiger** [comment]
Thanks again for the response @2x2xplz, we just released a new version which fixes the GitHub authentication issue. 

However, currently all GitHub users who sign-up for Wiredash who do not have a 'real name' set at that time will be called 'Anonymous' for now - we'll be adding the possibility to edit user details in the near future 🙂

Please let me know if all is working for you now and sorry for the inconvenience!
