### ISSUE TITLE
Dashboard: NPS score isn't displayed correctly

### ISSUE THREAD

**Issue by ciriousjoker** [wiredashio/wiredash-sdk#322]
**Describe the bug**
We get responses back, but the graph still shows no data for December. November worked flawlessly in this regard.

**Stacktrace**
_What's the stacktrace?_
Browser console is empty.

**Wiredash SDK Info**
_Which SDK are you using?_ 1.7.4
_On which platform are you seeing the crash?_ No crash, data is also submitted correctly

**Flutter SDK**
_Which Flutter version are you using? Run `flutter doctor -v`_
3.13.4/3.16.3 doesn't really matter.

**Screenshots**
- October was 0 because of a test submit
- November was tracked correctly
- December data seems to be missing
![CleanShot 2023-12-13 at 16 38 45@2x](https://github.com/wiredashio/wiredash-sdk/assets/16866223/ec27e2f7-dfb9-4dd0-aa28-b6b3ba3ce68c)

![CleanShot 2023-12-13 at 16 37 21@2x](https://github.com/wiredashio/wiredash-sdk/assets/16866223/5963b3fb-8fc5-4863-ae2e-8accec107f43)

**Comment by flschweiger** [comment]
Hey @ciriousjoker, thanks for reporting! We'll have a look and get back to you asap.

**Comment by ciriousjoker** [comment]
This isn't critical for us, since the data is still properly transmitted. Just the chart has a visual bug, but that can probably easily be fixed retroactively.

**Comment by flschweiger** [comment]
The issue has been resolved. Appreciate your assistance and the thorough details provided 👍 If you have additional thoughts about the product, please don't hesitate to share them with us 🙂
