### ISSUE TITLE
Unable to integrate email service with wiredash.

### ISSUE THREAD

**Issue by sanketWohlig** [wiredashio/wiredash-sdk#326]
**Describe the bug**
A clear and concise description of what the bug is and - at best - a clear way to reproduce it.
Try to adjust the `examples/` to reproduce the crash there.

**Stacktrace**
_What's the stacktrace?_
In browsers, check the `Console`.

**Wiredash SDK Info**
_Which SDK are you using?_
wiredash: ^1.7.8
_On which platform are you seeing the crash?_

**Flutter SDK**

_Which Flutter version are you using? Run `flutter doctor -v`_

**Screenshots**

I have received an email to verify my email account, but the link provided is invalid. As a result, I am unable to integrate the email service into my Wiredash account.
<img width="1440" alt="Screenshot 2024-01-08 at 11 44 34 AM" src="https://github.com/wiredashio/wiredash-sdk/assets/124883786/90a12e83-93ef-4195-a428-2abaad8a6544">

**Comment by flschweiger** [comment]
Hey @sanketWohlig, thanks for submitting this issue. Can you try deleting and re-adding the email again? The email should contain a valid link now. Let me know if that worked for you!
