### ISSUE TITLE
Add option to make email step required

### ISSUE THREAD

**Issue by flocbit** [wiredashio/wiredash-sdk#329]
**Is your feature request related to a problem? Please describe.**
Most of my users do not enter their email. But most of the times I need to ask follow up questions or I would like to inform them that I added their request.

**Describe the solution you'd like**
I would like to be able to make entering an email mandatory, e.g. `EmailPrompt.required`

**Describe alternatives you've considered**
Being able to customize the label above the email field to at least let users know that in order for me to respond to their request I need their email address.

**Comment by passsy** [comment]
This was very recently implemented and will be released soon

#327

**Comment by flocbit** [comment]
@passsy I'm happy to hear that! 😊

**Comment by passsy** [comment]
This is part of the 2.0.0 release!
