### ISSUE TITLE
Can't upgrade device_info_plus to newest version because of wiredash

### ISSUE THREAD

**Issue by sebastianbuechler** [wiredashio/wiredash-sdk#343]
**Describe the bug**
Wiredash 2.1.0 depends on device_info_plus >=8.0.0 <10.0.0, but since a month there's a new version of device_info_plus available: https://pub.dev/packages/device_info_plus/versions

**Stacktrace**
Because wiredash 2.1.0 depends on device_info_plus >=8.0.0 <10.0.0 and no versions of wiredash match >2.1.0 <3.0.0, wiredash ^2.1.0 requires device_info_plus >=8.0.0 <10.0.0.
So, because base depends on both device_info_plus ^10.1.0 and wiredash ^2.1.0, version solving failed.

**Wiredash SDK Info**
2.1.0

**Comment by passsy** [comment]
Fix has been released as [`2.1.1`](https://pub.dev/packages/wiredash/versions/2.1.1)
