### ISSUE TITLE
Show / Hide Wiredash FAB

### ISSUE THREAD

**Issue by rmadridm** [wiredashio/wiredash-sdk#41]
Just a question, do we have a way to show and hide the Wiredash FAB button? that is, not only show the Wiredash BottomSheet with:

`Wiredash.of(context).show();`

Any recommendation or provisional way?

Thanks for you attentions.

**Comment by rgbinnovation** [comment]
Would also very much like to see this feature, as I don't want to show it on all pages (login, for example).

**Comment by RegNex** [comment]
@Nash0x7E2 When should we expect this feature?
