### ISSUE TITLE
Using with BottomNavBar disables the first nav bar item

### ISSUE THREAD

**Issue by jwiese-ms** [wiredashio/wiredash-sdk#42]
When using Wiredash with a bottomnavbar I am no longer able to tap the first item in the nav bar. once I navigate to a second or third item the 1st is not a tap target.  If I remove wiredash all the code works correctly.

**Comment by orestesgaolin** [comment]
Hi @jwiese-ms, thanks for reporting this. Seems like this issue is the same as #26 and was fixed with #34 and should be deployed with next release. I'm not sure though when is it going to be published.

**Comment by flschweiger** [comment]
Hopefully tomorrow, so in less than 24 hours 😉

**Comment by flschweiger** [comment]
This fix is now available through version `0.2.0` 🍻
