### ISSUE TITLE
Is there an option to Delete a Feedback from the Console?

### ISSUE THREAD

**Issue by adiltirur** [wiredashio/wiredash-sdk#44]
While testing I added a lot of feedback and now I can only close, but is there a way to delete feedback or is something like this Already Planned?

**Comment by Nash0x7E2** [comment]
Hi @adiltirur thank you for raising this. We will be working on this feature very soon :)

**Comment by flschweiger** [comment]
I have been working on this, expect an update to the console shortly 🙂

**Comment by flschweiger** [comment]
This feature went live today 🙌
