### ISSUE TITLE
It is possible to send an empty (only whitespace) applause

### ISSUE THREAD

**Issue by AndroidNils** [wiredashio/wiredash-sdk#46]
## Steps to reproduce
1. Open Wiredash
2. Send applause
3. Press space
4. Send applause without email

![image](https://user-images.githubusercontent.com/24459435/83896230-1767ee00-a754-11ea-8f72-8f02751af2b8.png)

Same bug applies to a feature request and a bug report, if the user skips the screenshot.

## Fix
```
function isWhitespace(str: string): boolean {
    return str.match(/^\s*$/) !== null;
}
```

**Comment by orestesgaolin** [comment]
👏
