### ISSUE TITLE
Allow me revoke invites

### ISSUE THREAD

**Issue by passsy** [wiredashio/wiredash-sdk#5]
I did a typo when inviting members to my team. Nobody received the invite. I'd like to revoke it so it doesn't clutter my member list.

**Comment by flschweiger** [comment]
Thanks, that's actually on our to-do list. Right now not accepted invites are removed after 7 days when they become invalid 😉

**Comment by passsy** [comment]
Good to know!

**Comment by flschweiger** [comment]
Will probably be fixed together with #6

**Comment by flschweiger** [comment]
This is implemented now 👍
