### ISSUE TITLE
Feature: Email admin on new feedback

### ISSUE THREAD

**Issue by ghenry** [wiredashio/wiredash-sdk#50]
Hi,

I did three test feedbacks and expected wiredash.io to email me about them?

Thanks.

**Comment by flschweiger** [comment]
This will be rolled out as an integration in the upcoming days 🙂

**Comment by ghenry** [comment]
If it helps, we're Twilio SendGrid users.

**Comment by ghenry** [comment]
How's this going? I'm looking to release a version to customers and partners to test our login flow.

**Comment by flschweiger** [comment]
I'm working on it 🙂 Should be available over the weekend / on Monday when everything goes well. You also won't have to provide a separate API key for SendGrid, all should work out of the box 😃

**Comment by ghenry** [comment]
Excellent. Anything I can do to help?

**Comment by Dedecube** [comment]
Would really appreciate a feature like this

**Comment by flschweiger** [comment]
Thanks for all the input here, this feature is now available via the 'Integrations' tab on the console 🙌  📫  Let me know if you are missing something there. Slack will arrive soon as well 🚂

**Comment by ghenry** [comment]
The email that arrives is beautiful. Really nice work and well done.
