### ISSUE TITLE
Feature: Theming

### ISSUE THREAD

**Issue by ghenry** [wiredashio/wiredash-sdk#51]
Colours and pay to remove wiredash.io logo

**Comment by flschweiger** [comment]
You can already set custom colors to an extend, have a look at https://docs.wiredash.io/configuration/#theme-wiredashthemedata 🙂  The ability to upload a custom logo is on our roadmap as well - are you missing anything else?

**Comment by ghenry** [comment]
Cool! Read the docs! I forgot about the public docs :-) Thanks! I'll let you know if I do.
