### ISSUE TITLE
Feature: Changing all text

### ISSUE THREAD

**Issue by ghenry** [wiredashio/wiredash-sdk#52]
Use your own wording.

**Comment by flschweiger** [comment]
You can already provide a complete custom translation, check out https://docs.wiredash.io/configuration/#providing-custom-terms 😉  Let me know if you need any help or if you need something more special than what we currently provide.

**Comment by orestesgaolin** [comment]
Take a look at [this file](https://github.com/wiredashio/wiredash-sdk/blob/master/lib/src/common/translation/l10n/messages_en.dart) that may be useful as starting point for providing your own translations.

**Comment by ghenry** [comment]
Thanks!

**Comment by orestesgaolin** [comment]
In upcoming days (or weeks) we're going to add one or two more terms, but you should be warned about missing overrides in your analysis warnings. If you extend the above English localization class, then the default values will be used in place of missing terms.

**Comment by Nash0x7E2** [comment]
Hi @ghenry please see https://docs.wiredash.io/configuration/#providing-custom-terms

**Comment by liquidiert** [comment]
Hey @flschweiger, is there any other solution by now? The docs url unfortunately leads to nowhere.

**Comment by liquidiert** [comment]
Found it, it's now under: https://docs.wiredash.com/reference/sdk/localization#custom-strings
