### ISSUE TITLE
Website docs links 404

### ISSUE THREAD

**Issue by ghenry** [wiredashio/wiredash-sdk#53]
Bottom of:

https://docs.wiredash.io/guide/#_2-add-to-flutter

https://github.com/wiredashio/wiredash-sdk/edit/master/docs/configuration/README.md
https://github.com/wiredashio/wiredash-sdk/blob/nash/updated-sample/example/lib/main.dart

**Comment by flschweiger** [comment]
This should be fixed with the new docs and help pages 👍
