### ISSUE TITLE
Long User Id overflows in Console

### ISSUE THREAD

**Issue by ABausG** [wiredashio/wiredash-sdk#58]
Long User Ids Overflow in the Console when looking at a feedback

![image](https://user-images.githubusercontent.com/7288963/85513415-46f37300-b5fb-11ea-887d-e518d9ad37a4.png)

**Comment by flschweiger** [comment]
That's a long user id 😃  Will fix this asap!

**Comment by flschweiger** [comment]
This should be fixed in the newest update ✔️
