### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by ghenry** [wiredashio/wiredash-sdk#60]
Hi,

Just to say this is lovely, but could the email say what type of feedback it is? Bug, Applause, Feature request etc?

Thanks.

**Comment by flschweiger** [comment]
That's a great idea, will add more info to the emails soon 🙂

**Comment by flschweiger** [comment]
Hey @ghenry, just wanted to let you know that emails now contain the labels in the subject and even more info in the body - let us know if that's what you've been looking for 📮 

Closing this for now

**Comment by ghenry** [comment]
Awesome!
