### ISSUE TITLE
Integrate with existing support tools

### ISSUE THREAD

**Issue by IchordeDionysos** [wiredashio/wiredash-sdk#61]
Wiredash seems to be very cool and unique what it can do using Flutter. I don't expect something similar to large tools, like Intercom.

However, those tools have more sound support for team collaboration, Integrations with other services, ...

So using Wiredash together with, like Intercom, could be beneficial. Are there plans to generate screenshots that can be added to any new or existing Intercom conversation?

Maybe trough a standard API that allows to integrate any third-party tool?

**Comment by flschweiger** [comment]
Hey @IchordeDionysos, sorry for the late reply 🙈 We really like the idea to integrate with existing tools but what do you mean exactly by 'generating screenshots'? Do you want to generate an image from the feedback a user sent to attach it to Intercom? Or is it something else? Would love to hear your idea!

**Comment by passsy** [comment]
You can now connect all your favorite tools via Zapier

![zapier](https://docs.wiredash.io/images/zapier-dialog.png)

Checkout the docs https://docs.wiredash.io/integrations/zapier/
