### ISSUE TITLE
Boolean property when Wiredash UI is shown

### ISSUE THREAD

**Issue by IchordeDionysos** [wiredashio/wiredash-sdk#62]
There should be a property in the `WiredashController` telling me when the Wiredash UI shown.

I've built wrapper which shows Wiredash when shaking the phone, but that leads to some funny moments because a lot of Wiredash UIs are shown. See #63

Maybe `Wiredash.of(context).show()`, should only invoke ONE UI and ignore subsequent calls.

I'll upload a screen recording of it :D

**Comment by IchordeDionysos** [comment]
https://photos.app.goo.gl/hgvjBQZQ1NkgcSSz9

**Comment by D3m1tx** [comment]
I've the same problem.

**Comment by asteroid-studios** [comment]
I am dealing with this too

**Comment by ravipatelxongolab** [comment]
I am dealing with this too

**Comment by andyngdz** [comment]
Getting the same problem

**Comment by roughike** [comment]
> Maybe Wiredash.of(context).show(), should only invoke ONE UI and ignore subsequent calls.

This solution has been implemented in #81 and will be in the next release. Let us know if that will solve your use case!

Sounds like that would work for @IchordeDionysos and be enough to close this issue - what about you, @D3m1tx, @asteroid-studios, @ravipatelxongolab, @andyngdz, and @bulwinkel?

**Comment by andyngdz** [comment]
> > Maybe Wiredash.of(context).show(), should only invoke ONE UI and ignore subsequent calls.
> 
> This solution has been implemented in #81 and will be in the next release. Let us know if that will solve your use case!
> 
> Sounds like that would work for @IchordeDionysos and be enough to close this issue - what about you, @D3m1tx, @asteroid-studios, @ravipatelxongolab, @andyngdz, and @bulwinkel?

Thank you @roughike. It works for me as well

**Comment by andyngdz** [comment]
@roughike It works. Thanks a lot ;)
