### ISSUE TITLE
Github integration

### ISSUE THREAD

**Issue by jifalops** [wiredashio/wiredash-sdk#68]
How's this coming along?

Even if it just had the title and linked to the details on wiredash (#67), that'd be very helpful. Possibly tag it with `Wiredash` or just put `[wiredash]` in the title.

**Comment by passsy** [comment]
You can now connect all your favorite tools, including Github, via Zapier

![zapier](https://docs.wiredash.io/images/zapier-dialog.png)

Checkout the docs https://docs.wiredash.io/integrations/zapier/
