### ISSUE TITLE
Secret storage

### ISSUE THREAD

**Issue by ghenry** [wiredashio/wiredash-sdk#71]
Hi,

Just a quick question about whether or not the secret is recommended to be stored and retrieved from flutter_secure_storage for example?

Thanks.

**Comment by flschweiger** [comment]
Hi @ghenry 👋 

Calling the API key 'secret' may be a bit misleading but it should be fine if you just provide it through Dart code. The key is only used for providing feedback(you cannot retrieve anything with it) and we also have some abuse detection logic in place on our backend side 😉 Additionally we'll also add the feature to revoke a key in an upcoming release. 

However, adding a protective layer to your API keys is never a bad idea but it shouldn't be too much of an extra effort (depending on the type of key for sure).

Hope this helps, will also add an article to [help.wiredash.io](https://help.wiredash.o) 🙂 

Greetings from Germany!

**Comment by ghenry** [comment]
Thanks, understood.
