### ISSUE TITLE
Input Limit Feedback

### ISSUE THREAD

**Issue by ABausG** [wiredashio/wiredash-sdk#75]
We got several User Feedback from People who wanted to write more feedback than allowed by the limit of 512 Characters set by

https://github.com/wiredashio/wiredash-sdk/blob/35c23acba8111832a85a08ffa9d41bf562584fed/lib/src/feedback/components/input_component.dart#L157-L159

Especially giving the wording of
https://github.com/wiredashio/wiredash-sdk/blob/35c23acba8111832a85a08ffa9d41bf562584fed/lib/src/common/translation/l10n/intl_en.json#L21 
Suggested our User that they could provide longer feedback Texts

Is there a reason for this Limit? Could this be disabled/configured? And if not how would you feel about adding a Counter to show Users how many Characters they have left.

**Comment by flschweiger** [comment]
Thanks @ABausG for the feedback, we're planning on increasing this limit 👍

**Comment by flschweiger** [comment]
@passsy this has been increased already on the backend (up to 2048 chars), we just need to fix this in the SDK and show a counter when the user gets close to the limit 🚧

**Comment by passsy** [comment]
The limit has been raised to 2048 characters in [`v0.4.1`](https://github.com/wiredashio/wiredash-sdk/releases/tag/v0.4.1)
