### ISSUE TITLE
buildNumber doesn't show in Wiredash console

### ISSUE THREAD

**Issue by ghenry** [wiredashio/wiredash-sdk#78]
Hi,

Only the App Version (`buildVersion`) shows, but not `buildNumber` in the console. I'm setting all like so:

```
  Future<void> _wiredashFeedback() async {
    PackageInfo _packageInfo = await PackageInfo.fromPlatform();
    Wiredash.of(context).setUserProperties(
      userEmail: c.email,
      userId: c.accountNumber,
    );
    Wiredash.of(context).setBuildProperties(
      buildNumber: _packageInfo.buildNumber,
      buildVersion: _packageInfo.version,
    );
    Wiredash.of(context).show();
  }
```

Everything else does though.

Thanks.

**Comment by aseef17** [comment]
I would like this to be added to the console. Since the App Version (buildVersion) usually stays the same and the buildNumber is what increments when it's not a major release. Hope this gets added soon.

**Comment by flschweiger** [comment]
We'll add this to the updated console in the coming days 🙂

**Comment by flschweiger** [comment]
This just got fixed ✨ If you can't see the change yet, just refresh the page once 😉

**Comment by ghenry** [comment]
Thanks!

What is:

SDK Version < 0.5 - outdated
and

Flutter Version 2.10.2 (stable) (Tue Oct 13 15:50:27 2020 +0200) on
"android_arm64"

You mean Dart version?
