### ISSUE TITLE
Theme does not seem to work properly

### ISSUE THREAD

**Issue by stevsimo** [wiredashio/wiredash-sdk#86]
I have set the brightness in the WiredashThemeData to Theme.of(context).brightness.
If I have set my Theme to dark mode, i get a dark text on a dark background.

<img width="414" alt="WireDashDarkMode" src="https://user-images.githubusercontent.com/47678184/94136902-e841cd80-fe65-11ea-963e-c09aa3548edb.png">

**Comment by aguilaair** [comment]
Hey! How did you end up fixing it? The Theme.of(context).brightness will always return light as it is before initializing the theme on the MaterialApp so of course, I'm unable to use it. You also cannot use MediaQuery as that won't start until you have loaded the MaterialApp either.

Thanks!
