### ISSUE TITLE
Pass email address programmatically

### ISSUE THREAD

**Issue by yazinsai** [wiredashio/wiredash-sdk#9]
👋 First off, wonderful job with the SDK, I love it!

Right now, the user has to enter their email address manually in order to receive feedback on their, well, feedback:

<img width="342" alt="image" src="https://user-images.githubusercontent.com/1846034/81945163-6499e980-9606-11ea-9123-a845fb7c6e87.png">

Is there a way I can send the email address (which we already have) directly to WireDash and skip that step?

**Comment by flschweiger** [comment]
Hey, thanks for the feedback! Regarding the prefilling of the email, did you check out the `Wiredash.of(context).setOptions(userEmail, userId)` call? I guess that is exactly what you would need :)

**Comment by yazinsai** [comment]
@flschweiger wonderful! I thought the README or the example app would have all of the options illustrated. When I didn't see it there I guessed it didn't exist.

Should've checked the source code, I suppose! :)
